name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.commits.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Get commit hashes
        id: commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "hashes=[$(git log -z --pretty=format:"'%H'," \
              ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
              | sed 's/.$//')]" >> "$GITHUB_OUTPUT"
          else
            echo "hashes=['${{ github.sha }}']" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        commit: ${{ fromJson(needs.generate-matrix.outputs.commits) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: build
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Install tools
        run: cargo install --locked flip-link elf2uf2-rs
      - name: Build (cargo xtask dist)
        run: cargo xtask dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.commit }}
          path: build/
|
            build/combined.uf2
            build/application.uf2
            build/bootloader.uf2
